services:

  demo-java26:
    build:
      context: ../demo-java26
      dockerfile: Dockerfile
    container_name: demo-java26
    ports:
      - "8080:8080"
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=a932b4d9-8ca0-428e-9139-6bfb4260d1ef;IngestionEndpoint=https://indonesiacentral-0.in.applicationinsights.azure.com/;LiveEndpoint=https://indonesiacentral.livediagnostics.monitor.azure.com/;ApplicationId=0a24a181-faa8-4a08-9274-e2af6ac6ee60
      OTEL_SERVICE_NAME: iden-service
    networks:
      - app_net

  demo-cloud-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-cloud-app
    ports:
      - "8090:8090"
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=a932b4d9-8ca0-428e-9139-6bfb4260d1ef;IngestionEndpoint=https://indonesiacentral-0.in.applicationinsights.azure.com/;LiveEndpoint=https://indonesiacentral.livediagnostics.monitor.azure.com/;ApplicationId=0a24a181-faa8-4a08-9274-e2af6ac6ee60
      OTEL_SERVICE_NAME: demo-cloud-app
      MONGODB_URI: mongodb://mongodb:27017
      NUMBER_URL: http://demo-java26:8080
      NET_URL: http://dotnet-service:8085
    depends_on:
      - mongodb
    networks:
      - app_net

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
