server:
  port: ${PORT:8090}

spring:
  application:
    name: cloud-app

  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/cloud_app_db}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} [%level] [%thread] %logger - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} [%level] [traceId=%X{trace_id}] %logger - %msg%n"
  level:
    root: ${LOG_LEVEL:INFO}

  structured:
    json:
      rename:
        logger_name: class

api:
  number-service-url: ${NUMBER_URL:http://localhost:8080}